---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-migrate
  labels:
    project: example
    role: migrate
    team: foo
  annotations:
    samson/prerequisite: 'true'
data:
  data-1: value-1
  data-2: value-2
