# keep all files in sync ... check test/integration/kubernetes_test.rb
---
apiVersion: v1
kind: Pod
metadata:
  name: example-migrate
  labels:
    project: example
    role: migrate
  annotations:
    samson/prerequisite: 'true'
    samson/required_env: >
      RAILS_ENV
spec:
  restartPolicy: Never
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  containers:
  - name: default
    image: replaced-by-samson
    args: ["ruby", "-e", "puts 'MIGRATE'"]
    resources:
      requests:
        cpu: '0.1'
        memory: '100Mi'
      limits:
        cpu: '0.5'
        memory: '300Mi'
    env:
    - name: SERVE_STATIC_ASSETS
      value: 'true'
    - name: RAILS_LOG_TO_STDOUT
      value: 'true'
