# keep all files in sync ... check test/integration/kubernetes_test.rb
---
apiVersion: batch/v1
kind: Job
metadata:
  name: example-server
  annotations:
    samson/prerequisite: 'true'
  labels:
    project: example
    role: server
spec:
  template:
    metadata:
      labels:
        project: example
        role: server
      annotations:
        samson/required_env: >
          RAILS_ENV
    spec:
      restartPolicy: OnFailure # by default 6 tries
      containers:
      - name: default
        image: replaced-by-samson
        command: ["echo", "hello"]
        resources:
          requests:
            cpu: '0.1'
            memory: '100Mi'
          limits:
            cpu: '0.5'
            memory: '300Mi'
        env:
        - name: SERVE_STATIC_ASSETS
          value: 'true'
        - name: RAILS_LOG_TO_STDOUT
          value: 'true'
