# keep all files in sync ... check test/integration/kubernetes_test.rb
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-server
  labels:
    project: example
    role: server
    team: foo
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: '25%'
  selector:
    matchLabels:
      project: example
      role: server
  template:
    metadata:
      labels:
        project: example
        role: server
        team: foo
      annotations:
        samson/required_env: >
          RAILS_ENV
    spec:
      priorityClassName: noooped
      containers:
      - name: default
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1
          runAsNonRoot: true
        image: replaced-by-samson
        resources:
          requests:
            cpu: '100'
            memory: '100Mi'
          limits:
            cpu: '0.5'
            memory: '300Mi'
        env:
        - name: SERVE_STATIC_ASSETS
          value: 'true'
        - name: RAILS_LOG_TO_STDOUT
          value: 'true'
