# keep all files in sync ... check test/integration/kubernetes_test.rb
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  labels:
    project: example
    role: server
    a: a
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      labels:
        project: example
        role: server
        b: b
    spec:
      template:
        metadata:
          labels:
            project: example
            role: server
            c: c
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
